# Generated by Django 2.1.2 on 2018-10-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page_template',
            name='banner',
            field=models.CharField(default='Banner values go in here', max_length=200),
        ),
    ]
